# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_companyinvite_familyinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinvite',
            old_name='family',
            new_name='company',
        ),
    ]
